In [3]:
#importing numpy
#converting list to arrays in python
import numpy as np

list = [1,2,3,4,5]
print(list)
arr = np.array(list)
print(arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [44]:
#creating a matrix using numpy, and defining matrix
import numpy as np

matrix = np.array([[1,2,3] , [4,5,6]])
print(matrix)
print("Size of the above matrix is:",matrix.shape)
print("Data type of the matrix is:",matrix.dtype)

[[1 2 3]
 [4 5 6]]
Size of the above matrix is: (2, 3)
Data type of the matrix is: int64


In [21]:
#creating an array of zeroes and ones

zeros = np.zeros((4,8))
print("Matrix of Zeroes:")
print(zeros)

print("Matrix of Ones:")
ones = np.ones((4,8))
print(ones)

Matrix of Zeroes:
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
Matrix of Ones:
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [44]:
#matix with range of numbers
import numpy as np

#arange operation
range_arr = np.arange(0,10,3) #prints the first number, and futher steps in the given number and prints within the range
print(range_arr)

#linspace operation
range_arr = np.linspace(0,10,3) #gives the parts of the given range. ex: number line
print(range_arr)


[0 3 6 9]
[ 0.  5. 10.]


In [31]:
# arranging arrray to matrix with "reshape" operation and back to 1d using "flatten" operaion
import numpy as np

#reshape
print("Reshape operation:")
arr = np.arange(12).reshape(4,3)
print(arr)

array = np.array([[1,2,3],[4,5,6]])
print("\n",array)

#flatten
print("\nFlatten operation:")
flat = array.flatten()
print(flat)

Reshape operation:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

 [[1 2 3]
 [4 5 6]]

Flatten operation:
[1 2 3 4 5 6]


In [121]:
#Creating array and performing array Operations: min, max, sum, slicing
import numpy as np

arr = np.array([1,2,3,3,3,4,5])
print("Array:",arr)

print("Minimum value:",arr.min()) #min value
print("Maximum Value:",arr.max()) #max value
print("Sum of values in array:",arr.sum()) #sum 
print("Sliced array by 3:",arr[:3]) #slicing array


Array: [1 2 3 3 3 4 5]
Minimum value: 1
Maximum Value: 5
Sum of values in array: 21
Sliced array by 3: [1 2 3]


In [75]:
#Creating ana array and finding mean, median and standard deviation
import numpy as np

arr = np.array([1,2,3,4,5])
print("Mean:",np.mean(arr))
print("Median:",np.median(arr))
print("Standard Deviation:",np.std(arr))

Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951


In [84]:
#Creating a 2D aray and performing few operations: slicing, accessing specific element
import numpy as np

matrix = np.array([[1,2,3,],[4,5,6]])
print("Matrix:")
print(matrix)

#slicing
print("\nSliced Matrix:")
print(matrix[:,2])

#specific element
print("\nSpecific Element:")
print(matrix[0,1])

Matrix:
[[1 2 3]
 [4 5 6]]

Sliced Matrix:
[3 6]

Specific Element:
2


In [89]:
# Array Operations with other arrays\
import numpy as np

arr1 = np.array([1,3,5,7,9,11])
arr2 = np.array([2,4,6,8,10,12])

#performing element-wise addition
print(arr1 + arr2)

#performing element-wise muliplication
print(arr1 * arr2)

[ 3  7 11 15 19 23]
[  2  12  30  56  90 132]


In [115]:
# Matrix Operations: multiplication
import numpy as np

mat1 = np.array([[1,2,3],[6,7,8]])
mat2 = np.array([[2,4,6],[1,2,3],[1,2,3]])
print("Matrix 1:\n",mat1)
print("\nMatrix 2:\n",mat2)

#Matrix Multiplication(Dot)
print("\nDot Product:\n",np.dot(mat1, mat2))

#Transpose
print("\nTranspose:\n",mat1.T)


Matrix 1:
 [[1 2 3]
 [6 7 8]]

Matrix 2:
 [[2 4 6]
 [1 2 3]
 [1 2 3]]

Dot Product:
 [[ 7 14 21]
 [27 54 81]]

Transpose:
 [[1 6]
 [2 7]
 [3 8]]


In [88]:
#More array Operation: unique, replcing
import numpy as np

arr = np.array([1,2,3,3,3,4,5])
print("Array:",arr)

#finding unique elemnts only
print("Uniques:",np.unique(arr))

#replacing elements based on condition
arr[arr==3]=0
print("Replced by 0 if element is 3:",arr)




Array: [1 2 3 3 3 4 5]
Uniques: [1 2 3 4 5]
Replced by 0 if element is 3: [1 2 0 0 0 4 5]


In [90]:
#array sorting and shuffling elements of the array
import numpy as np
arr = np.arange(10)
print("Original array:",arr)
np.random.shuffle(arr)
print("Shuffled array:",arr)

#sorting: sorts in ascending order
array = np.array([9,3,6,4,2,8])
print("\n")
print("Original array:",array)
print("Sorted array:",np.sort(array))

Original array: [0 1 2 3 4 5 6 7 8 9]
Shuffled array: [6 8 7 5 3 9 1 0 2 4]


Original array: [9 3 6 4 2 8]
Sorted array: [2 3 4 6 8 9]


In [34]:
#stacking arrays horizontally and vertically

x = np.array([[1,2,3],[3,4,5]])
y = np.array([[9,8,7],[3,4,5]])

print(x)
print("\n",y)
print("\nhstack:\n",np.hstack((x,y)))

print("\nvstack:\n",np.vstack((x,y)))

[[1 2 3]
 [3 4 5]]

 [[9 8 7]
 [3 4 5]]

hstack:
 [[1 2 3 9 8 7]
 [3 4 5 3 4 5]]

vstack:
 [[1 2 3]
 [3 4 5]
 [9 8 7]
 [3 4 5]]


In [36]:
#calculates correlation coefficient matrix between two ARRAYS
print(np.corrcoef(x,y))

[[ 1.  1. -1.  1.]
 [ 1.  1. -1.  1.]
 [-1. -1.  1. -1.]
 [ 1.  1. -1.  1.]]


In [41]:
#save and load numpy array
np.save('array.npy',arr)
loaded = np.load('array.npy')
print(loaded)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
